# Generated by Django 4.1 on 2022-08-24 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='tech_stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporations.techstack', verbose_name='기술스택'),
        ),
    ]
